# Generated by Django 5.2.6 on 2025-10-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bearer_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
