# Generated by Django 5.2.5 on 2025-09-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_tokens_used_alter_user_username_usertokenusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTokenUsage',
        ),
    ]
